<a href="https://colab.research.google.com/github/Redcoder815/Deep_Learning_TensorFlow/blob/main/09ParameterManagement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu),
    tf.keras.layers.Dense(1),
])

X = tf.random.uniform((2, 4))
net(X).shape

TensorShape([2, 1])

In [3]:
net.layers[2].weights

[<Variable path=sequential/dense_1/kernel, shape=(4, 1), dtype=float32, value=[[-0.77511644]
  [-1.0237864 ]
  [ 0.46134806]
  [-0.2841375 ]]>,
 <Variable path=sequential/dense_1/bias, shape=(1,), dtype=float32, value=[0.]>]

In [4]:
type(net.layers[2].weights[1]), tf.convert_to_tensor(net.layers[2].weights[1])

(keras.src.backend.Variable,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)

In [5]:
net.get_weights()

[array([[-0.6854594 ,  0.37959427,  0.02542472,  0.08344108],
        [-0.5931681 , -0.116256  ,  0.2846015 , -0.527899  ],
        [-0.85496277, -0.74533737, -0.8515991 ,  0.33614713],
        [ 0.54150575,  0.5643161 ,  0.39413816, -0.08967191]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.77511644],
        [-1.0237864 ],
        [ 0.46134806],
        [-0.2841375 ]], dtype=float32),
 array([0.], dtype=float32)]

In [6]:
# tf.keras behaves a bit differently. It removes the duplicate layer
# automatically
shared = tf.keras.layers.Dense(4, activation=tf.nn.relu)
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    shared,
    shared,
    tf.keras.layers.Dense(1),
])

net(X)
# Check whether the parameters are different
print(len(net.layers) == 3)
print(len(net.layers) == 4)

False
True
