<a href="https://colab.research.google.com/github/Redcoder815/Deep_Learning_TensorFlow/blob/main/10ParameterInitialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu),
    tf.keras.layers.Dense(1),
])

X = tf.random.uniform((2, 4))
net(X).shape

TensorShape([2, 1])

Normal distribution

In [5]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4, activation=tf.nn.relu,
        kernel_initializer=tf.random_normal_initializer(mean=0, stddev=0.01),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1)])

net(X)
net.weights[0], net.weights[1]

(<Variable path=sequential_3/dense_6/kernel, shape=(4, 4), dtype=float32, value=[[-0.00516491 -0.00813296 -0.00450728 -0.00144148]
  [ 0.00671426 -0.00963134  0.00899311 -0.00660089]
  [-0.01046472 -0.00766879 -0.00957938  0.01322725]
  [ 0.02031519 -0.03299486 -0.01375613 -0.00029919]]>,
 <Variable path=sequential_3/dense_6/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>)

Constant

In [6]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4, activation=tf.nn.relu,
        kernel_initializer=tf.keras.initializers.Constant(1),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1),
])

net(X)
net.weights[0], net.weights[1]

(<Variable path=sequential_4/dense_8/kernel, shape=(4, 4), dtype=float32, value=[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]>,
 <Variable path=sequential_4/dense_8/bias, shape=(4,), dtype=float32, value=[0. 0. 0. 0.]>)

Xavier initializer

In [7]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4,
        activation=tf.nn.relu,
        kernel_initializer=tf.keras.initializers.GlorotUniform()),
    tf.keras.layers.Dense(
        1, kernel_initializer=tf.keras.initializers.Constant(42)),
])

net(X)
print(net.layers[1].weights[0])
print(net.layers[2].weights[0])

<Variable path=sequential_5/dense_10/kernel, shape=(4, 4), dtype=float32, value=[[ 0.747588   -0.07072359 -0.08660471  0.5757186 ]
 [ 0.69835943  0.38258392  0.12049949 -0.22841096]
 [-0.23633575 -0.03385431  0.20794207 -0.28407395]
 [ 0.6942877  -0.5449967   0.70316964  0.195167  ]]>
<Variable path=sequential_5/dense_11/kernel, shape=(4, 1), dtype=float32, value=[[42.]
 [42.]
 [42.]
 [42.]]>


Custom initialization

In [8]:
class MyInit(tf.keras.initializers.Initializer):
    def __call__(self, shape, dtype=None):
        data=tf.random.uniform(shape, -10, 10, dtype=dtype)
        factor=(tf.abs(data) >= 5)
        factor=tf.cast(factor, tf.float32)
        return data * factor

net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4,
        activation=tf.nn.relu,
        kernel_initializer=MyInit()),
    tf.keras.layers.Dense(1),
])

net(X)
print(net.layers[1].weights[0])

<Variable path=sequential_6/dense_12/kernel, shape=(4, 4), dtype=float32, value=[[-5.069902  -8.114262   6.158819  -6.733105 ]
 [ 0.         0.        -0.         0.       ]
 [ 5.0887184  0.         7.6730194  6.7936935]
 [ 9.475832   5.6642838 -0.         0.       ]]>


In [9]:
net.layers[1].weights[0][:].assign(net.layers[1].weights[0] + 1)
net.layers[1].weights[0][0, 0].assign(42)
net.layers[1].weights[0]

<Variable path=sequential_6/dense_12/kernel, shape=(4, 4), dtype=float32, value=[[42.        -7.1142616  7.158819  -5.733105 ]
 [ 1.         1.         1.         1.       ]
 [ 6.0887184  1.         8.673019   7.7936935]
 [10.475832   6.6642838  1.         1.       ]]>